from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup, name='signup'),
    path('student_dashboard/', views.student_dashboard, name='student_dashboard'),
    path('teacher_dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('logout/', views.logout_view, name='logout'),
    path('placement_test/', views.placement_test, name='placement_test'),
    path('reservation-success/', views.reservation_success, name='reservation_success'),
    path('get-reserved-times/', views.get_reserved_times, name='get_reserved_times'),
    path('search-students/', views.search_students, name='search_students'),
    path('add-student/', views.add_student_to_course, name='add_student_to_course'),
    path('courses/', views.courses_list, name='courses_list'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('course/<int:course_id>/remove_student/<int:student_id>/', views.remove_student_from_course, name='remove_student_from_course'),
    path('course/<int:course_id>/student/<int:student_id>/grade/', views.set_student_grade, name='set_student_grade'),
    path('course/<int:course_id>/student/<int:student_id>/remove/', views.remove_student_from_course, name='remove_student_from_course'),
    path('set-level/<int:student_id>/', views.set_student_level, name='set_student_level'),
    path('courses/<int:course_id>/request/', views.send_enrollment_request, name='send_enrollment_request'),
    path('teacher/requests/', views.view_requests, name='teacher_requests'),
    path('course/<int:course_id>/delete/', views.delete_course, name='delete_course'),
    path('student/profile/<int:student_id>/', views.student_profile_detail, name='student_profile_detail'),
    path('course/<int:course_id>/set_link/', views.set_course_link, name='set_course_link'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('teachers/', views.teacher_list, name='teacher_list'),
    path('rate/<int:teacher_id>/', views.rate_teacher, name='rate_teacher'),
    path('courses/<int:course_id>/assignments/', views.assignment_list_create, name='assignment_list_create'),
    path('course/<int:course_id>/assignments/', views.student_assignments_view, name='student_course_assignments'),
    path('assignments/<int:assignment_id>/submissions/', views.assignment_submissions_view, name='assignment_submissions'),
    path('course/<int:course_id>/assignments/', views.student_assignments_view, name='student_assignments_view'),
    path('teacher/assignment/<int:assignment_id>/submissions/', views.assignment_submissions_view, name='assignment_submissions_view'),
]

