# Generated by Django 4.2.23 on 2025-07-09 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_days',
            field=models.CharField(choices=[('Monday-Wednesday', 'Monday-Wednesday'), ('Tuesday-Thursday', 'Tuesday-Thursday'), ('Only Fridays', 'Only Fridays')], max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.CharField(choices=[('8-10 am', '8-10 am'), ('10-12 am', '10-12 am'), ('1-3 pm', '1-13 pm'), ('3-5 pm', '3-5 pm'), ('5-7 pm', '5-7 pm'), ('8-12 am', '8-12 am')], max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='required_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Upper Intermediate', 'Upper Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
    ]
