# Generated by Django 4.2.23 on 2025-07-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_course_students_alter_course_class_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_time',
            field=models.CharField(choices=[('8-10 am', '8-10 am'), ('10-12 am', '10-12 am'), ('1-3 pm', '1-3 pm'), ('3-5 pm', '3-5 pm'), ('5-7 pm', '5-7 pm'), ('8-12 am', '8-12 am')], max_length=50),
        ),
    ]
