# Generated by Django 4.2.23 on 2025-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_link',
            field=models.URLField(default='#'),
        ),
    ]
