# Generated by Django 4.2.23 on 2025-07-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_enrollmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Korean', 'Korean'), ('Chinese', 'Chinese')], default='English', max_length=50),
            preserve_default=False,
        ),
    ]
