# Generated by Django 4.2.23 on 2025-07-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_class_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/images/default.png', upload_to='static/images/'),
        ),
    ]
