# Generated by Django 4.2.23 on 2025-07-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='class_language',
        ),
    ]
