# Generated by Django 4.2.23 on 2025-07-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_course_class_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
