# Generated by Django 4.2.23 on 2025-07-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_teacherschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSchedule',
        ),
    ]
