# Generated by Django 4.2.23 on 2025-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_topic_conversation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='topic',
            field=models.CharField(choices=[('Reading Skills', 'Reading Skills'), ('English Grammar', 'English Grammar'), ('Speaking', 'Speaking'), ('Vocabulary and Idiom', 'Vocabulary and Idiom'), ('Daily Life', 'Daily Life'), ('Fun', 'Fun'), ('Social Topics', 'Social Topics'), ('Movies', 'Movies'), ('Books', 'Books'), ('Music', 'Music')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
