# Generated by Django 4.2.23 on 2025-09-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtestreservation',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='placementtestreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
