# Generated by Django 4.2.23 on 2025-09-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_placementtestreservation_assigned_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementtestreservation',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
