# Generated by Django 4.2.23 on 2025-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_exam_examsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='graded',
            field=models.BooleanField(default=False),
        ),
    ]
